# -*- coding: utf-8 -*-

"""
Geometric parameters
"""

MIN_SEPARATION_THRESHOLD = 1e-10
MIN_VECTOR_MAGNITUDE = 1e-9
MIN_SCALAR_VALUE = 1e-12
MIN_POINT_POS_DIFF = MIN_SCALAR_VALUE
MIN_ANGLE_DEGR_VALUE = 1e-6
MIN_VECTOR_MAGN_DIFF = MIN_SCALAR_VALUE
MIN_ANGLE_DEGR_DISORIENTATION = 5.
VECTOR_ANGLE_THRESHOLD = 1
PLANE_ANGLE_THRESHOLD = 1
DIP_ANGLE_THRESHOLD = 5

angle_gplane_thrshld = 2.5  # dip angle threshold, degrees
rake_threshold = 5.0  # rake, degrees

